[package]
name = "ferra"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11.8"
gl33 = "0.2.1"
glfw = "0.59.0"
image = "0.25.6"
log = "0.4.27"
thiserror = "2.0.12"
